"""Stateful Agent Runtime domain primitives.

This package deliberately has no database, HTTP, Provider, or model imports.
It defines the contracts that the durable executor will use when the legacy
TaskRunner is migrated incrementally.
"""

from app.runtime.adapters import (
    build_runtime_handler_registry,
    register_internal_agent_handler,
    register_provider_handler,
    register_subagent_handlers,
    register_tool_handlers,
)
from app.runtime.contracts import (
    AgentRun,
    AgentRunPlan,
    DecisionAction,
    RuntimeBudget,
    RuntimeCompatibilitySnapshot,
    RuntimeDecision,
    RuntimeEffectStatus,
    RuntimeGoal,
    RuntimeLaunchSnapshot,
    RuntimeNode,
    RuntimeNodeState,
    RuntimeNodeStatus,
    RuntimeObservation,
    RuntimePlanBudgetImpact,
    RuntimePlanProposal,
    RuntimePlanProposalStatus,
    RuntimeRunStatus,
)
from app.runtime.controller import (
    ControlProvider,
    DecisionEventHook,
    PlanProposalProvider,
    RuntimeController,
    RuntimeRunSuspended,
)
from app.runtime.event_bridge import (
    RUNTIME_EVENT_TYPES,
    build_runtime_observability,
    to_task_event,
)
from app.runtime.executor import (
    PlanExecutor,
    RuntimeBatchHook,
    RuntimeEventHook,
    RuntimeNodeError,
    RuntimeNodeSuspended,
)
from app.runtime.goal_planner import (
    RuntimeCapabilitySelection,
    RuntimeGoalPlanner,
    RuntimeGoalPlannerError,
    RuntimeGoalPlanResult,
)
from app.runtime.handler_registry import (
    RuntimeHandlerDescriptor,
    RuntimeHandlerRegistry,
    RuntimeHandlerRegistryError,
)
from app.runtime.plan_proposal_eval import (
    RuntimePlanProposalEvaluationCase,
    RuntimePlanProposalEvaluationResult,
    RuntimePlanProposalSemanticExpectation,
    RuntimePlanProposalSuite,
    RuntimePlanProposalSuiteReport,
    evaluate_runtime_plan_proposal,
    evaluate_runtime_plan_proposal_suite,
)
from app.runtime.replay import (
    RuntimeCanaryEvidence,
    RuntimeCanaryPair,
    RuntimeCanaryPairResult,
    RuntimeCanaryReport,
    RuntimeCanarySuite,
    RuntimeCanaryThresholds,
    RuntimeCheckpointRecord,
    RuntimeEvaluationCase,
    RuntimeEvaluationResult,
    RuntimeLegacyDiffReport,
    RuntimeParitySnapshot,
    RuntimeTraceAudit,
    audit_checkpoint_trace,
    build_runtime_legacy_diff,
    build_runtime_parity_snapshot,
    evaluate_runtime_canary_pair,
    evaluate_runtime_canary_suite,
    evaluate_runtime_run,
)
from app.runtime.solver_parity import (
    SolverParityPair,
    SolverParityPairResult,
    SolverParitySuite,
    SolverParitySuiteReport,
    SolverParityThresholds,
    evaluate_solver_parity_pair,
    evaluate_solver_parity_suite,
)
from app.runtime.state_machine import RuntimeStateMachine
from app.runtime.subagents import (
    RuntimeSubagentDefinition,
    RuntimeSubagentRegistry,
    RuntimeSubagentRegistryError,
)

__all__ = [
    "AgentRun",
    "AgentRunPlan",
    "DecisionAction",
    "RuntimeBudget",
    "RuntimeDecision",
    "RuntimeGoal",
    "RuntimeNode",
    "RuntimeNodeState",
    "RuntimeNodeStatus",
    "RuntimeEffectStatus",
    "RuntimeObservation",
    "RuntimeLaunchSnapshot",
    "RuntimeCompatibilitySnapshot",
    "RuntimePlanBudgetImpact",
    "RuntimePlanProposal",
    "RuntimePlanProposalStatus",
    "RuntimeRunStatus",
    "RuntimeStateMachine",
    "PlanExecutor",
    "RuntimeBatchHook",
    "RuntimeEventHook",
    "RuntimeNodeError",
    "RuntimeNodeSuspended",
    "RUNTIME_EVENT_TYPES",
    "build_runtime_observability",
    "to_task_event",
    "RuntimeController",
    "ControlProvider",
    "DecisionEventHook",
    "PlanProposalProvider",
    "RuntimeRunSuspended",
    "build_runtime_handler_registry",
    "register_tool_handlers",
    "register_provider_handler",
    "register_internal_agent_handler",
    "register_subagent_handlers",
    "RuntimeSubagentDefinition",
    "RuntimeSubagentRegistry",
    "RuntimeSubagentRegistryError",
    "RuntimeHandlerDescriptor",
    "RuntimeHandlerRegistry",
    "RuntimeHandlerRegistryError",
    "RuntimeCapabilitySelection",
    "RuntimeGoalPlanResult",
    "RuntimeGoalPlanner",
    "RuntimeGoalPlannerError",
    "RuntimeCheckpointRecord",
    "RuntimeCanaryPair",
    "RuntimeCanaryPairResult",
    "RuntimeCanaryReport",
    "RuntimeCanarySuite",
    "RuntimeCanaryThresholds",
    "RuntimeCanaryEvidence",
    "RuntimeTraceAudit",
    "RuntimeEvaluationCase",
    "RuntimeEvaluationResult",
    "RuntimeLegacyDiffReport",
    "RuntimeParitySnapshot",
    "audit_checkpoint_trace",
    "build_runtime_legacy_diff",
    "build_runtime_parity_snapshot",
    "evaluate_runtime_canary_pair",
    "evaluate_runtime_canary_suite",
    "evaluate_runtime_run",
    "RuntimePlanProposalEvaluationCase",
    "RuntimePlanProposalEvaluationResult",
    "RuntimePlanProposalSemanticExpectation",
    "RuntimePlanProposalSuite",
    "RuntimePlanProposalSuiteReport",
    "evaluate_runtime_plan_proposal",
    "evaluate_runtime_plan_proposal_suite",
    "SolverParityPair",
    "SolverParityPairResult",
    "SolverParitySuite",
    "SolverParitySuiteReport",
    "SolverParityThresholds",
    "evaluate_solver_parity_pair",
    "evaluate_solver_parity_suite",
]
