/** Cross-course math expressions used by the single frontend renderer. */
export const MATH_FIXTURES = [
  String.raw`Z_C=\frac{1}{j\omega C}`,
  String.raw`y(t)=\int_{-\infty}^{+\infty}x(\tau)h(t-\tau)\,d\tau`,
  String.raw`i_C=C\frac{du_C}{dt}`,
  String.raw`\frac{\partial f}{\partial x}`,
  String.raw`X[k]=\sum_{n=0}^{N-1}x[n]e^{-j2\pi kn/N}`,
  String.raw`\begin{bmatrix}a&b\\c&d\end{bmatrix}`,
  String.raw`\begin{cases}x+1,&x>0\\0,&x\le 0\end{cases}`,
  String.raw`\begin{aligned}u_o&=A(u_+-u_-)\\i&=\frac{u}{R}\end{aligned}`,
  String.raw`10\angle30^\circ\,\mathrm{V}`,
  String.raw`\lim_{t\to\infty}e^{-t}=0`,
  String.raw`\sqrt{x^2+y^2}`,
  String.raw`\frac{V_o}{V_i}=\frac{-R_f}{R_1}`,
  String.raw`\omega_0=\frac{1}{\sqrt{LC}}`,
  String.raw`H(j\omega)=\frac{1}{1+j\omega RC}`,
  String.raw`v(t)=V_m\cos(\omega t+\phi)`,
  String.raw`\hat{x}=\arg\min_x\|Ax-b\|_2^2`,
  String.raw`P(A\mid B)=\frac{P(B\mid A)P(A)}{P(B)}`,
  String.raw`\sum_{k=0}^{\infty}r^k=\frac{1}{1-r}`,
  String.raw`\int_0^T|x(t)|^2\,dt`,
  String.raw`\nabla\cdot\mathbf{E}=\frac{\rho}{\varepsilon_0}`,
  String.raw`\mathbf{F}=m\mathbf{a}`,
  String.raw`\mathbf{Z}=\begin{bmatrix}R&j\omega L\\1/(j\omega C)&R\end{bmatrix}`,
  String.raw`\left|\begin{matrix}a&b\\c&d\end{matrix}\right|=ad-bc`,
  String.raw`x[n]=x[n-1]+u[n]`,
  String.raw`f_s\ge 2f_{\max}`,
  String.raw`\mathrm{SNR}=10\log_{10}\frac{P_s}{P_n}`,
  String.raw`\Delta t=\frac{1}{f_s}`,
  String.raw`\Pr(Y=y)=\binom{n}{y}p^y(1-p)^{n-y}`,
  String.raw`\mu=\frac{1}{n}\sum_{i=1}^{n}x_i`,
  String.raw`\sigma^2=\frac{1}{n-1}\sum_{i=1}^{n}(x_i-\mu)^2`,
  String.raw`\mathrm{FFT}(x)[k]=\sum_{n=0}^{N-1}x[n]e^{-j2\pi kn/N}`,
] as const;

export const MATH_FIXTURE_COUNT = MATH_FIXTURES.length;
