from __future__ import annotations

LOCAL_AGENT_IMPLEMENTATIONS: dict[str, str] = {
    "TEACH_01_LESSON_PREP_V1": "LESSON_PREP_LOCAL_V1",
    "TEACH_02_ASSIGNMENT_REVIEW_V1": "ASSIGNMENT_REVIEW_LOCAL_V1",
    "RESEARCH_02_ACADEMIC_WRITING_V1": "ACADEMIC_WRITING_LOCAL_V1",
    "RESEARCH_03_DATA_ANALYSIS_V1": "DATA_ANALYSIS_LOCAL_V1",
}
