from app.providers.retrieval.academic import (
    AcademicSearchProvider,
    AcademicSearchService,
    ArxivAcademicProvider,
    CnkiAcademicProvider,
    CrossrefAcademicProvider,
    OpenAlexAcademicProvider,
    SemanticScholarAcademicProvider,
    merge_academic_results,
)
from app.providers.retrieval.adapters import (
    ArxivQueryAdapter,
    CrossrefQueryAdapter,
    OpenAlexQueryAdapter,
    ProviderQuery,
    ProviderQueryAdapter,
    ProviderSearchContext,
)
from app.providers.retrieval.factory import create_external_search_service
from app.providers.retrieval.web import (
    AliyunIqsSearchProvider,
    BochaSearchProvider,
    BraveSearchProvider,
    JsonWebSearchProvider,
    NewsRssSearchProvider,
    SearxngSearchProvider,
    SerpApiSearchProvider,
    TavilySearchProvider,
)

__all__ = [
    "AcademicSearchProvider",
    "AcademicSearchService",
    "ArxivQueryAdapter",
    "CrossrefQueryAdapter",
    "ArxivAcademicProvider",
    "CnkiAcademicProvider",
    "CrossrefAcademicProvider",
    "OpenAlexAcademicProvider",
    "SemanticScholarAcademicProvider",
    "merge_academic_results",
    "JsonWebSearchProvider",
    "TavilySearchProvider",
    "BraveSearchProvider",
    "SerpApiSearchProvider",
    "AliyunIqsSearchProvider",
    "BochaSearchProvider",
    "SearxngSearchProvider",
    "NewsRssSearchProvider",
    "create_external_search_service",
    "OpenAlexQueryAdapter",
    "ProviderQuery",
    "ProviderQueryAdapter",
    "ProviderSearchContext",
]
